debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*" # show hidden actuator endpoint
logging:
  level:
    com.fastcampus.board_project: debug # ?? ??? ??? ??? ??
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: yhs
    password: yhs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # ???? ?????? ??
    hibernate:
      ddl-auto: update # ???? ???? ???? ??? ??
    show-sql: true # sql ?? ??
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  sql:
    init:
      mode: never
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true



---

